# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kouya/rv32ima

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kouya/rv32ima

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kouya/rv32ima/CMakeFiles /home/kouya/rv32ima//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kouya/rv32ima/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named elf

# Build rule for target.
elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 elf
.PHONY : elf

# fast build rule for target.
elf/fast:
	$(MAKE) $(MAKESILENT) -f elf/CMakeFiles/elf.dir/build.make elf/CMakeFiles/elf.dir/build
.PHONY : elf/fast

src/_main.o: src/_main.cpp.o
.PHONY : src/_main.o

# target to build an object file
src/_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/_main.cpp.o
.PHONY : src/_main.cpp.o

src/_main.i: src/_main.cpp.i
.PHONY : src/_main.i

# target to preprocess a source file
src/_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/_main.cpp.i
.PHONY : src/_main.cpp.i

src/_main.s: src/_main.cpp.s
.PHONY : src/_main.s

# target to generate assembly for a file
src/_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/_main.cpp.s
.PHONY : src/_main.cpp.s

src/bus.o: src/bus.cpp.o
.PHONY : src/bus.o

# target to build an object file
src/bus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/bus.cpp.o
.PHONY : src/bus.cpp.o

src/bus.i: src/bus.cpp.i
.PHONY : src/bus.i

# target to preprocess a source file
src/bus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/bus.cpp.i
.PHONY : src/bus.cpp.i

src/bus.s: src/bus.cpp.s
.PHONY : src/bus.s

# target to generate assembly for a file
src/bus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/bus.cpp.s
.PHONY : src/bus.cpp.s

src/csr.o: src/csr.cpp.o
.PHONY : src/csr.o

# target to build an object file
src/csr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/csr.cpp.o
.PHONY : src/csr.cpp.o

src/csr.i: src/csr.cpp.i
.PHONY : src/csr.i

# target to preprocess a source file
src/csr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/csr.cpp.i
.PHONY : src/csr.cpp.i

src/csr.s: src/csr.cpp.s
.PHONY : src/csr.s

# target to generate assembly for a file
src/csr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/csr.cpp.s
.PHONY : src/csr.cpp.s

src/disassembler.o: src/disassembler.cpp.o
.PHONY : src/disassembler.o

# target to build an object file
src/disassembler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/disassembler.cpp.o
.PHONY : src/disassembler.cpp.o

src/disassembler.i: src/disassembler.cpp.i
.PHONY : src/disassembler.i

# target to preprocess a source file
src/disassembler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/disassembler.cpp.i
.PHONY : src/disassembler.cpp.i

src/disassembler.s: src/disassembler.cpp.s
.PHONY : src/disassembler.s

# target to generate assembly for a file
src/disassembler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/disassembler.cpp.s
.PHONY : src/disassembler.cpp.s

src/processor.o: src/processor.cpp.o
.PHONY : src/processor.o

# target to build an object file
src/processor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/processor.cpp.o
.PHONY : src/processor.cpp.o

src/processor.i: src/processor.cpp.i
.PHONY : src/processor.i

# target to preprocess a source file
src/processor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/processor.cpp.i
.PHONY : src/processor.cpp.i

src/processor.s: src/processor.cpp.s
.PHONY : src/processor.s

# target to generate assembly for a file
src/processor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/processor.cpp.s
.PHONY : src/processor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... elf"
	@echo "... main"
	@echo "... src/_main.o"
	@echo "... src/_main.i"
	@echo "... src/_main.s"
	@echo "... src/bus.o"
	@echo "... src/bus.i"
	@echo "... src/bus.s"
	@echo "... src/csr.o"
	@echo "... src/csr.i"
	@echo "... src/csr.s"
	@echo "... src/disassembler.o"
	@echo "... src/disassembler.i"
	@echo "... src/disassembler.s"
	@echo "... src/processor.o"
	@echo "... src/processor.i"
	@echo "... src/processor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

